name: cloud-resume-ci

on:
 push:
  branches: [ main ]

jobs:
 
 build:
  
  runs-on: ubuntu-latest
  
  
  steps:
  
  - name: git-checkout
    uses: actions/checkout@v3

  - name: Setup Terraform
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_wrapper: false

  - name: Terraform Init
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    id: init
    run: terraform init
    working-directory: ./terraform

  - name: Terraform apply
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    id: apply
    run: terraform apply -auto-approve
    working-directory: ./terraform

  - name: Set output
    id: set-dns
    run: |-
      echo "::set-output name=instance_public_dns::$(terraform output ec2_public_ip)"
    working-directory: ./terraform

  - run: echo SERVER_PUBLIC_IP=${{ steps.set-dns.outputs.instance_public_dns }} >> $GITHUB_ENV

  - name: Build & push Docker image
    uses: mr-smithers-excellent/docker-build-push@v6
    with:
      image: tma1314/docker-hub-repo
      tags: v1, latest
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: wait for server
    run: sleep 90

  - name: copy docker-compose via ssh key
    uses: appleboy/scp-action@master
    with:
      host: ${{ env.SERVER_PUBLIC_IP }}
      username: ubuntu
      key: ${{ secrets.KEY }}
      source: "docker-compose.yaml"
      target: "/home/ubuntu"

  - name: copy docker-compose via ssh key
    uses: appleboy/scp-action@master
    with:
      host: ${{ env.SERVER_PUBLIC_IP }}
      username: ubuntu
      key: ${{ secrets.KEY }}
      source: "script-cmnds.sh"
      target: "/home/ubuntu"

  - name: Deploy Docker Image to EC2
    env:
     IMAGE_TAG: ${{ github.sha }}
    uses: appleboy/ssh-action@master
    with:
      host: ${{ env.SERVER_PUBLIC_IP }}
      username: ubuntu
      key: ${{ secrets.KEY }}
      script: |
       sudo chmod +x script-cmnds.sh
       export URL="tma1314/docker-hub-repo"
       export IMAGE=$IMAGE_TAG
       export docker_user=${{ secrets.DOCKER_USERNAME }}
       export docker_pswd=${{ secrets.DOCKER_PASSWORD }}
       sudo bash script-cmnds.sh 

